# @url = https://localhost:44335
@url = https://localhost:5001
#@url = https://api.votemonitor.org
# @url = http://localhost:53413

# @name observerJwtToken
POST {{url}}/api/v2/access/authorize
Content-Type: application/json

{
  "user": "074",
  "password": "1234",
  "channelName": "a channel name",
  "fcmToken": "fcmToken"
}
###

# @name observerJwtToken
POST {{url}}/api/v1/access/authorize
Content-Type: application/json

{
  "user": "074",
  "password": "1234",
  "uniqueId": "a channel name"
}
###
# @name adminJwtToken
POST {{url}}/api/v2/access/authorize
Content-Type: application/json

{
  "user": "admin@code4ro.org",
  "password": "password"
}
###

# @name getCounties
GET {{url}}/api/v1/county
Content-Type: application/json
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}
###

# @name getMunicipalities
GET {{url}}/api/v1/county/0201/municipalities
Content-Type: application/json
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}
###

# @name getCounty
GET {{url}}/api/v1/county/1
Content-Type: application/json
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}
###

# @name getPollingStations
GET {{url}}/api/v2/polling-station
Content-Type: application/json
Authorization: Bearer {{observerJwtToken.response.body.$.access_token}}
###

# @name statisticsMiniAll
GET {{url}}/api/v1/statistics/mini/all
Content-Type: application/json
Authorization: Bearer {{observerJwtToken.response.body.$.access_token}}
###


# @name flaggedanswersStatistics
GET {{url}}/api/v1/statistics/mini/flaggedanswers
Content-Type: application/json
Authorization: Bearer {{observerJwtToken.response.body.$.access_token}}
###

# @name loggedinobserversStatistics
GET {{url}}/api/v1/statistics/mini/loggedinobservers
Content-Type: application/json
Authorization: Bearer {{observerJwtToken.response.body.$.access_token}}
###

# @name notesStatistics
GET {{url}}/api/v1/statistics/mini/notes
Content-Type: application/json
Authorization: Bearer {{observerJwtToken.response.body.$.access_token}}
###


# @name countiesStatistics
GET {{url}}/api/v1/statistics/mini/counties
Content-Type: application/json
Authorization: Bearer {{observerJwtToken.response.body.$.access_token}}
###

# @name stationsStatistics
GET {{url}}/api/v1/statistics/mini/stations
Content-Type: application/json
Authorization: Bearer {{observerJwtToken.response.body.$.access_token}}
###

# @name answersStatistics
GET {{url}}/api/v1/statistics/mini/answers
Content-Type: application/json
Authorization: Bearer {{observerJwtToken.response.body.$.access_token}}
###

# @name countAnswersByQuestion
GET {{url}}/api/v1/statistics/countAnswersByQuestion
  ?QuestionId=7
Content-Type: application/json
Authorization: Bearer {{observerJwtToken.response.body.$.access_token}}
###


# @name uploadNotes
POST {{url}}/api/v2/note
Authorization: Bearer {{observerJwtToken.response.body.$.access_token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="CountyCode"

3263
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="MunicipalityCode"

326301
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="PollingStationNumber"

23
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Text"

a text
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Files"; filename="1.jpg"
Content-Type: image/jpg

< ./image1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###
# @name registerNotification
POST {{url}}/api/v1/notification/register
Content-Type: application/json
Authorization: Bearer {{observerJwtToken.response.body.$.access_token}}

{
  "observerId": 1,
  "channelName": "string",
  "token": "string"
}
###
# @name sendNotification
POST {{url}}/api/v1/notification/send/all
Content-Type: application/json
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}

{
  "channel": "string",
  "from": "string",
  "title": "string",
  "message": "string"
}
###

# @name getFormVersions
GET {{url}}/api/v1/form/versions
Authorization: Bearer {{observerJwtToken.response.body.$.access_token}}
###

# @name getForms
GET {{url}}/api/v1/form
Authorization: Bearer {{observerJwtToken.response.body.$.access_token}}
###

# @name getFormDetails
GET {{url}}/api/v1/form/1
Authorization: Bearer {{observerJwtToken.response.body.$.access_token}}
###

###
# @name importForms
POST {{url}}/api/v1/form
Content-Type: application/json
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}

< EN-C.json
###

###
# @name countyCsvFormat
GET {{url}}/api/v1/county/csvFormat
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}
###

###
# @name getObserversImportTemplate
GET {{url}}/api/v1/observer/import-template
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}
###

###
# @name getProvinceImportTemplate
GET {{url}}/api/v1/province/import-template
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}
###

###
# @name getCountyImportTemplate
GET {{url}}/api/v1/county/import-template
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}
###

###
# @name getMunicipalitiesImportTemplate
GET {{url}}/api/v1/municipality/import-template
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}
###

###
# @name getPollingStationsImportTemplate
GET {{url}}/api/v1/polling-station/import-template
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}
###

###
# @name importObservers
POST {{url}}/api/v1/observer/import
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="ngoId"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="observers.csv"
Content-Type: text/csv

< ./observers.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

###
# @name importProvinces
POST {{url}}/api/v1/province/import
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="CsvFile"; filename="provinces.csv"
Content-Type: text/csv

< ./polish_provinces_2023.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

###
# @name importCounties
POST {{url}}/api/v1/county/import
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="CsvFile"; filename="counties.csv"
Content-Type: text/csv

< ./polish_counties_2023.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

###
# @name importMunicipalities
POST {{url}}/api/v1/municipality/import
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="CsvFile"; filename="municipalities.csv"
Content-Type: text/csv

< ./polish_municipalities_2023.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

###
# @name addPollingStationsDetails
POST {{url}}/api/v1/polling-station
Authorization: Bearer {{observerJwtToken.response.body.$.access_token}}
Content-Type: application/json

{
        "countyCode": "3263",
        "municipalityCode": "326301",
        "pollingStationNumber": 22,
        "observerArrivalTime": "2023-10-13T23:35:11",
        "numberOfVotersOnTheList": 77,
        "numberOfCommissionMembers": 99,
        "numberOfFemaleMembers": 44,
        "minPresentMembers": 3,
        "chairmanPresence": true,
        "singlePollingStationOrCommission": false,
        "adequatePollingStationSize": true
    }
###

###
# @name importPollingStations
POST {{url}}/api/v1/polling-station/import
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="CsvFile"; filename="polling-stations.csv"
Content-Type: text/csv

< ./polish_polling_stations_2023.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

###
# @name exportAll
GET {{url}}/api/v2/export/all
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}
###

###
# @name getNgos
GET {{url}}/api/v1/ngo
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}
###

###
# @name getObservers
GET {{url}}/api/v1/observer
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}
###


# @name addNgo
POST {{url}}/api/v1/ngo
Content-Type: application/json
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}

{
  "shortName": "FOP",
  "name": "Fundacja Odpowiedzialna Polityka",
  "organizer": true,
  "isActive": true
}
###

###
# @name prefillCache
GET {{url}}/api/v1/locations-cache/prefill
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}
###

###
# @name prefillCache
GET {{url}}/api/v1/polling-station/polling-stations-cache/prefill
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}
###

###
# @name getPollingStations
GET {{url}}/api/v1/polling-station
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}
###

###
# @name getObservers
GET {{url}}/api/v1/observer?Name=&Number=074&Page=1&PageSize=100
Authorization: Bearer {{adminJwtToken.response.body.$.access_token}}
###