name: Publish Docker image

on:

  push:
    branches:
      - develop
      - master

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Save branch name
        run: echo "##[set-output name=BRANCH;]$(if [ ${GITHUB_REF#refs/heads/} == "master" ]; then echo "prod"; else echo "dev"; fi)"
        id: branch

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.ORGANIZATION }}/${{ secrets.REPO }}:${{ steps.branch.outputs.BRANCH }}
